- name: Create ansible group
  group:
    name: ansible
    system: yes
    state: present
  tags: users

- name: Create users
  user:
    name: "{{ item.name }}"
    update_password: on_create
    password: "{{ item.initpassword | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
    groups: ansible
  with_items: "{{ users }}"
  tags: users
  ignore_errors: "{{ ansible_check_mode }}"